const buttonDefaultText = "🦑 Generate Titles";

function addButton() {
  if (!window.location.href.includes("studio.youtube.com/video/")) {
    return;
  }

  const buttons = document.querySelector(".ytcp-entity-page-header .buttons");

  if (buttons) {
    let button = document.querySelector("#ToobSquidBtn");
    if (button) {
      return;
    }
    button = document.createElement("button");
    button.textContent = buttonDefaultText;
    button.id = "ToobSquidBtn";
    button.onclick = async () => {
      button.innerText = "Doing the magic 🪄";
      button.classList.add("generating");
      const response = await chrome.runtime.sendMessage({
        message: "transcribe",
      });

      // message.message is a string then we have an error
      if (typeof response.message === "string") {
        button.innerText = buttonDefaultText;
        button.classList.remove("generating");
        alert(response.message);
        return;
      }

      // message.message is an object then we have a success
      const { title, description, hashtags, timeStamps } = response.message;

      const textArea = document.querySelector(
        "#title-textarea ytcp-social-suggestion-input .ytcp-social-suggestions-textbox"
      );
      const descriptionArea = document.querySelector(
        "#description-textarea ytcp-social-suggestion-input .ytcp-social-suggestions-textbox"
      );

      const timestamps = timeStamps.length
        ? "⏱️ TIMESTAMPS" +
          "\n" +
          timeStamps.reduce(
            (acc, ts) => acc + "\n" + ts.timestamp + " - " + ts.topic,
            ""
          )
        : "";

      textArea.innerText = title;
      textArea.dispatchEvent(new Event("input"));

      setTimeout(() => {
        const existingText = descriptionArea.innerText;
        const existingMatch = existingText.match(
          /### Generated by ToobSquid https:\/\/ai.toobsquid.com ###/
        );

        const newText =
          existingMatch !== null
            ? description +
              "\n\n" +
              hashtags.join(" ") +
              "\n\n" +
              "### Generated by ToobSquid https://ai.toobsquid.com ###" +
              "\n\n" +
              timestamps +
              "\n\n" +
              existingText.split(
                /### Generated by ToobSquid https:\/\/ai.toobsquid.com ###/
              )[1]
            : description +
              "\n\n" +
              hashtags.join(" ") +
              "\n\n" +
              timestamps +
              "\n\n" +
              "### Generated by ToobSquid https://ai.toobsquid.com ###" +
              "\n\n" +
              existingText;

        descriptionArea.innerHTML = newText;
        descriptionArea.dispatchEvent(new Event("input"));

        button.innerText = buttonDefaultText;
        button.classList.remove("generating");
      }, 1000);
    };
    buttons.prepend(button);
  }
}

setInterval(addButton, 1000);
