const buttons = document.querySelector(".ytcp-entity-page-header .buttons");

if (buttons) {
  const button = document.createElement("button");
  button.textContent = "ToobSquid";
  button.onclick = async () => {
    button.innerText = "Transcribing...";
    const response = await chrome.runtime.sendMessage({
      message: "transcribe",
    });

    // message.message is a string then we have an error
    if (typeof response.message === "string") {
      button.innerText = "ToobSquid";
      alert(response.message);
      return;
    }

    // message.message is an object then we have a success
    const { title, description, hashtags } = response.message;
    console.log(title, description, hashtags);

    document.querySelector(
      "#title-textarea ytcp-social-suggestion-input .ytcp-social-suggestions-textbox"
    ).value = title;

    // Need to make sure we overwrite the just our part of the description
    document.querySelector(
      "#description-container ytcp-social-suggestion-input .ytcp-social-suggestions-textbox"
    ).value =
      description +
      "\n\n" +
      hashtags.join(" ") +
      "\n\n" +
      "### Generated by ToobSquid https://toobsquid.com ###" +
      "\n\n" +
      "" +
      document.querySelector(
        "#description-container ytcp-social-suggestion-input .ytcp-social-suggestions-textbox"
      ).innerText;

    button.innerText = "ToobSquid";
  };
  buttons.prepend(button);
}
