console.log("toobsquid content.js");

function addButton() {
  if (!window.location.href.includes("studio.youtube.com/video/")) {
    return;
  }

  const buttons = document.querySelector(".ytcp-entity-page-header .buttons");

  if (buttons) {
    let button = document.querySelector("#ToobSquidBtn");
    if (button) {
      return;
    }
    button = document.createElement("button");
    button.textContent = "ToobSquid";
    button.id = "ToobSquidBtn";
    button.onclick = async () => {
      button.innerText = "Doing the magic🪄";
      const response = await chrome.runtime.sendMessage({
        message: "transcribe",
      });

      // message.message is a string then we have an error
      if (typeof response.message === "string") {
        button.innerText = "ToobSquid";
        alert(response.message);
        return;
      }

      // message.message is an object then we have a success
      const { title, description, hashtags } = response.message;
      console.log(title, description, hashtags);

      document.querySelector(
        "#title-textarea ytcp-social-suggestion-input .ytcp-social-suggestions-textbox"
      ).value = title;

      const existingText = document.querySelector(
        "#description-container ytcp-social-suggestion-input .ytcp-social-suggestions-textbox"
      ).innerText;
      const existingMatch = existingText.match(
        /### Generated by ToobSquid https:\/\/toobsquid.com ###/
      );

      document.querySelector(
        "#description-container ytcp-social-suggestion-input .ytcp-social-suggestions-textbox"
      ).value = existingMatch
        ? description +
          "\n\n" +
          hashtags.join(" ") +
          "\n\n" +
          "### Generated by ToobSquid https://toobsquid.com ###" +
          "\n\n" +
          "" +
          existingText.split(
            "### Generated by ToobSquid https://toobsquid.com ###"
          )[1]
        : description +
          "\n\n" +
          hashtags.join(" ") +
          "\n\n" +
          "### Generated by ToobSquid https://toobsquid.com ###" +
          "\n\n" +
          "" +
          document.querySelector(
            "#description-container ytcp-social-suggestion-input .ytcp-social-suggestions-textbox"
          ).innerText;

      button.innerText = "ToobSquid";
    };
    buttons.prepend(button);
  }
}

setInterval(addButton, 1000);
